### ISSUE TITLE
The embedded video is 404

### ISSUE THREAD

**Issue by remram44** [media-streaming-mesh/mediastreamingmesh.io#197]
The URL is https://www.mediastreamingmesh.io/assets/shared/mediastreamingmesh.mp4

![screenshot](https://user-images.githubusercontent.com/426784/218269595-46f666d2-678d-4012-a241-0534d67bc615.png)

**Comment by gilesheron** [comment]
we'll get this one fixed ASAP

**Comment by gilesheron** [comment]
fixed by PR #207

will upload a new video to YouTube shortly.
